---
all:
  hosts:
    titan:
      ansible_host: 192.168.56.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/titan/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3.11
      vagrant:
        vm:
          box: Leap-15.6.x86_64
          box_url: https://download.opensuse.org/distribution/leap/15.6/appliances/boxes/Leap-15.6.x86_64.json
          box_version: 15.6.19.56
          cpus: 3
          memory: 4096
          gui: false

    rhea:
      ansible_host: 192.168.56.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/rhea/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3.11
      vagrant:
        vm:
          box: Leap-15.5.x86_64
          box_url: https://download.opensuse.org/distribution/leap/15.5/appliances/boxes/Leap-15.5.x86_64.json
          box_version: 15.5.13.309
          cpus: 3
          memory: 4096
          gui: false

  children:
    webservers:
      hosts:
        titan:
        rhea:
