---
nginx:
  version: null
  checksum: null

nginx_user: "{{ ansible_user }}"
nginx_user_home: "{{ ansible_user_dir }}"
nginx_src_directory: "{{ nginx_user_home }}/src"

nginx_build_configuration:
  - --add-module=../../modsecurity-nginx/{{ modsecurity_nginx.version }}
  - --with-debug
  - --with-http_auth_request_module
  - --with-http_gzip_static_module
  - --with-http_ssl_module
  - --with-http_stub_status_module
  - --with-http_v2_module
  - --with-pcre
  - --without-http_browser_module
  - --without-http_empty_gif_module
  - --without-http_fastcgi_module
  - --without-http_geo_module
  - --without-http_memcached_module
  - --without-http_referer_module
  - --without-http_scgi_module
  - --without-http_split_clients_module
  - --without-http_ssi_module
  - --without-http_upstream_hash_module
  - --without-http_upstream_ip_hash_module
  - --without-http_upstream_zone_module
  - --without-http_userid_module
  - --without-http_uwsgi_module

nginx_confd_files: []

nginx_confd_templates: []

nginx_vhosts_files: []

nginx_vhosts_templates:
  - vhosts/default.conf.j2

# http://nginx.org/en/docs/ngx_core_module.html
nginx_core_module:
  accept_mutex: null
  accept_mutex_delay: null
  daemon: null
  debug_connection: []
  debug_points: null
  env: []
  error_log_level: null
  master_process: null
  multi_accept: null
  pcre_jit: null
  ssl_engine: null
  thread_pool: null
  timer_resolution: null
  use: null
  worker_aio_requests: null
  worker_connections: null
  worker_cpu_affinity: null
  worker_priority: null
  worker_processes: null
  worker_rlimit_core: null
  worker_rlimit_nofile: null
  worker_shutdown_timeout: null

nginx_logrotate_rotate: 180
