---
- name: Ensure package is present.
  community.general.zypper:
    name:
      - logrotate
    state: present
  become: true

- name: Ensure required directories are present.
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    mode: "0700"
  loop:
    - { dest: "{{ logrotate_user_home }}/etc/logrotate.d/daily.d" }
    - { dest: "{{ logrotate_user_home }}/var/lib/logrotate" }
    - { dest: "{{ logrotate_user_home }}/var/log" }
    - { dest: "{{ logrotate_user_home }}/.config/systemd/user" }

- name: Ensure logrotation configuration is present.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0600"
  loop:
    - { src: "daily.conf.j2", dest: "{{ logrotate_user_home }}/etc/logrotate.d/daily.conf" }
    - { src: "logrotate.j2", dest: "{{ logrotate_user_home }}/etc/logrotate.d/daily.d/logrotate" }

- name: Ensure systemd user service file.
  ansible.builtin.template:
    src: logrotate.service.j2
    dest: "{{ logrotate_user_home }}/.config/systemd/user/logrotate.service"
    mode: "0600"
  notify: logrotate changed

- name: Ensure systemd user timer file.
  ansible.builtin.template:
    src: logrotate.timer.j2
    dest: "{{ logrotate_user_home }}/.config/systemd/user/logrotate.timer"
    mode: "0600"
  notify: logrotate changed

- name: Check if user is lingering.
  ansible.builtin.stat:
    path: /var/lib/systemd/linger/{{ logrotate_user }}
  register: logrotate_user_lingering

- name: Enable user lingering.
  ansible.builtin.command: loginctl enable-linger {{ logrotate_user }}
  when: not logrotate_user_lingering.stat.exists
  changed_when: true
  become: true
