---
- name: Ensure build dependencies are present.
  community.general.zypper:
    name:
      - gcc
      - make
      - xz
    state: present
  become: true

- name: Ensure required directories are present.
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    mode: "0700"
  loop:
    - { dest: "{{ quickjs_src_directory }}/download" }
    - { dest: "{{ quickjs_src_directory }}/quickjs/{{ quickjs_version }}" }
    - { dest: "{{ quickjs_user_home }}/bin" }
    - { dest: "{{ quickjs_user_home }}/include/quickjs" }
    - { dest: "{{ quickjs_user_home }}/lib/quickjs" }

- name: Ensure »QuickJS« source is present.
  ansible.builtin.get_url:
    url: https://bellard.org/quickjs/quickjs-{{ quickjs_version }}.tar.xz
    dest: "{{ quickjs_src_directory }}/download/quickjs-{{ quickjs_version }}.tar.xz"
    checksum: "{{ quickjs_checksum }}"
    mode: "0600"

- name: Ensure »»QuickJS«« source is extracted.
  ansible.builtin.unarchive:
    src: "{{ quickjs_src_directory }}/download/quickjs-{{ quickjs_version }}.tar.xz"
    dest: "{{ quickjs_src_directory }}/quickjs/{{ quickjs_version }}"
    remote_src: true
    extra_opts:
      - --strip-components=1
    mode: u=rwX,g=,o=

- name: Ensure artifacts are build.
  community.general.make:
    chdir: "{{ quickjs_src_directory }}/quickjs/{{ quickjs_version }}"
    jobs: "{{ (ansible_processor_nproc * 0.75) | round(0, 'floor') | int }}"
    params:
      PREFIX: "{{ quickjs_user_home }}"
  register: quickjs_make

- name: Ensure binary artifacts are striped.
  # noqa: no-handler
  ansible.builtin.command:
    argv: ["strip", "{{ item }}"]
    chdir: "{{ quickjs_src_directory }}/quickjs/{{ quickjs_version }}"
  loop:
    - qjs
    - qjsc
  when: quickjs_make.changed
  changed_when: quickjs_make.changed

- name: Ensure artifacts are present.
  ansible.builtin.copy:
    src: "{{ quickjs_src_directory }}/quickjs/{{ quickjs_version }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - { src: "qjs", dest: "{{ quickjs_user_home }}/bin", mode: "u=rwx,g=,o=" }
    - { src: "qjsc", dest: "{{ quickjs_user_home }}/bin", mode: "u=rwx,g=,o=" }
    - { src: "libquickjs.a", dest: "{{ quickjs_user_home }}/lib/quickjs", mode: "u=rw,g=,o=" }
    - { src: "libquickjs.lto.a", dest: "{{ quickjs_user_home }}/lib/quickjs", mode: "u=rw,g=,o=" }
    - { src: "quickjs.h", dest: "{{ quickjs_user_home }}/include/quickjs", mode: "u=rw,g=,o=" }
    - { src: "quickjs-libc.h", dest: "{{ quickjs_user_home }}/include/quickjs", mode: "u=rw,g=,o=" }
